services:
#  job:
#    container_name: thermocron_job_dev
#    image: thomasthiry/thermocron:2025-02-24.4
#    environment:
#     - thermocronMullerUsername=${thermocron_muller_username}
#     - thermocronMullerPassword=${thermocron_muller_password}
#     - thermocronMullerHomeId=${thermocron_muller_home_id}
#     - connectionString=Host=thermocron_db_dev:5432;Database=thermocron_dev;Username=${thermocron_postgres_user_dev};Password=${thermocron_postgres_password_dev}
  api:
    container_name: thermocron_api_dev
    image: thomasthiry/thermocron-api:2025-06-29.2
    ports:
      - "8080:8080"
    environment:
     - connectionString=Host=thermocron_db_dev:5432;Database=thermocron_dev;Username=${thermocron_postgres_user_dev};Password=${thermocron_postgres_password_dev}
  web:
    container_name: thermocron_web_dev
    image: thomasthiry/thermocron-web:2025-06-29.4
    ports:
      - "443:443"
      - "80:80"
  db:
    container_name: thermocron_db_dev
    image: postgres
    ports:
      - "15432:5432"
    volumes:
      - thermocron_sqldata_dev:/thermocron_sqldata
    environment:
      - POSTGRES_USER=${thermocron_postgres_user_dev}
      - POSTGRES_PASSWORD=${thermocron_postgres_password_dev}
      - PGDATA=/thermocron_sqldata

volumes:
  thermocron_sqldata_dev: